# Generated by Django 5.2.4 on 2025-07-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='TestField',
            field=models.CharField(null=True),
        ),
    ]
