# Generated by Django 5.2.4 on 2025-08-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='TestField',
        ),
    ]
